version: "3"

services:
  datadog:
    image: gcr.io/datadoghq/agent:7

    environment:
      - DD_LOGS_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_SITE=${DD_SITE:-datadoghq.com}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_API_KEY=${DD_API_KEY:?No API Key provided}
      - DD_HOSTNAME=${DD_HOSTNAME:?No Hostname provided}

    ports:
      # CFC3
      - 127.0.0.1:56543:56543/udp
      - 127.0.0.1:${DD_DOGSTATSD_PORT:-8125}:8125/udp

    volumes:
      - ./gmod.d:/etc/datadog-agent/conf.d/gmod.d/:ro
